parameters:
- name: JiraEnvironment
  type: string
  values:
  - Unmapped
  - Development
  - Testing
  - Staging
  - Production
- name: preDeploySteps
  type: stepList
  default: []
- name: deploySteps
  type: stepList
  default: []
- name: environment
  type: string
  default: ''
  
variables:
- name: envName
  ${{ if eq(parameters.environment, '') }}:
    value: ${{parameters.JiraEnvironment}}
  ${{ else }}:
    value: ${{parameters.environment}}
jobs:
- deployment: ${{ parameters.JiraEnvironment }}
  environment: $(envName)
  strategy:
    runOnce:
      preDeploy:
        steps:
          - template: $(Build.SourcesDirectory)/update-jira.yml
            parameters: 
              JiraState: "Pending"
              JiraEnvironment: ${{ parameters.JiraEnvironment }}
          - ${{ parameters.preDeploySteps }}
      on:
        failure:
          steps:
            - template: $(Build.SourcesDirectory)/update-jira.yml
              parameters: 
                JiraState: "Failed"
                JiraEnvironment: ${{ parameters.JiraEnvironment }}
        success: 
          steps:
            - template: $(Build.SourcesDirectory)/update-jira.yml
              parameters: 
                JiraState: "Successful"
                JiraEnvironment: ${{ parameters.JiraEnvironment }}
      deploy:
        steps:
          - template: $(Build.SourcesDirectory)/update-jira.yml
            parameters: 
              JiraState: "InProgress"
              JiraEnvironment: ${{ parameters.JiraEnvironment }}
          - ${{ parameters.deploySteps }}
